import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import ClickSpark from "@/components/layout/click-spark";
import { LenisProvider } from "@/components/layout/lenis-provider";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClickSpark sparkColor="#C5A55A" sparkSize={12} sparkRadius={20} sparkCount={8} duration={400} easing="ease-out">
          <LenisProvider>{children}</LenisProvider>
        </ClickSpark>
      </body>
    </html>
  );
}
